# Generated by Django 3.2 on 2021-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=1, max_length=100, verbose_name='IconText'),
            preserve_default=False,
        ),
    ]
