# Generated by Django 3.2 on 2021-04-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.CharField(default=1, max_length=25, verbose_name='Link Reference'),
            preserve_default=False,
        ),
    ]
