# Generated by Django 3.2 on 2021-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_portfolio_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_div_class',
            field=models.CharField(default=1, max_length=25, verbose_name='Portfolio div class'),
            preserve_default=False,
        ),
    ]
