# Generated by Django 3.2 on 2021-04-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfolio_portfolio_div_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_div_class',
            new_name='div_class',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_link',
            new_name='link',
        ),
    ]
