# Generated by Django 3.2 on 2021-04-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_portfoliomodal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodal',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfoliomodal',
            name='portfoliomodals',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfoliomodals', to='home.portfolio'),
            preserve_default=False,
        ),
    ]
