# Generated by Django 3.2 on 2021-04-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210427_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodal',
            name='portfoliomodals',
        ),
        migrations.AddField(
            model_name='portfoliomodal',
            name='portfoliomodal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfoliomodal', to='home.portfolio'),
            preserve_default=False,
        ),
    ]
