# Generated by Django 3.2 on 2021-04-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210427_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='div_class',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
    ]
