# Generated by Django 3.2 on 2021-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210427_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
